---

- name: Create start command in /etc/rc.local
  lineinfile:
    path: /etc/rc.local
    line: /usr/local/sbin/cloudsshkey
    regexp: '/usr/local/sbin/cloudsshkey'
    mode: 0644
    create: yes
