---

- name: Install cloudsshkey
  template:
    src: cloudsshkey.j2
    dest: /usr/local/sbin/cloudsshkey
    mode: 0755
    validate: sh -n %s

- name: Install wget
  openbsd_pkg:
    name: wget
    state: present

- name: Install cloud_set_guest_password.j2
  template:
    src: cloud_set_guest_password.j2
    dest: /usr/local/sbin/cloud_set_guest_password
    mode: 0755
    validate: sh -n %s
