---
# tasks file for ansible-role-cloudstack_init

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- include: "configure-{{ ansible_os_family }}.yml"

- name: Remove dhclient.leases files
  file:
    name: "{{ cloudstack_init_dhclient_lease_dir }}/dhclient.leases.{{ item }}"
    state: absent
  with_items: {{ cloudstack_init_interfaces }}
